if [ -f "$HOME/nano-highlight/.Nano-highlight-exists" ]; then
  echo "nano-highlight folder exists, skipping folder setup..."
  cd $HOME/nano-highlight
else
  if [ -f "$HOME/.nanorc" ]
  then
    mv ~/.nanorc ~/.nanoconf
    echo "Your nano config has been moved to $HOME/.nanoconf."
    echo "Edit that file to add configs besides the loader."
  else
    echo -e "# DO NOT DELETE THIS FILE!\nIt is provided by nano-highlight to offer\n# working config other than the highlighting loader.\n" > ~/.nanoconf
  fi
  echo -n "Setting up highlighter folder..."
  mkdir $HOME/nano-highlight
  cd $HOME/nano-highlight
  touch .Nano-highlight-exists
  wget https://raw.githubusercontent.com/TylerMS887/nano-highlight/main/README-installed-full -O README -q
  echo " Done!"
fi
echo "Downloading highlighters [latest version]..."
echo -e -n "\r- Dart"
wget https://raw.githubusercontent.com/TylerMS887/nano-highlight/main/.dart.nanorc -q
echo -e "\r✓ Dart"
echo "Enabling highlighters..."
echo "include \"$HOME/nano-highlight/.*.nanorc\"" > $HOME/.nanorc
echo -e "include \"$HOME/.nanoconf\"\n\n# DO NOT EDIT THIS FILE!\n# Edit $HOME/.nanoconf instead." >> $HOME/.nanorc
if [ -f "$HOME/nano-highlight/README" ]
then
  cat README
  rm README
fi
echo "Installation finished!"
# alert
echo -en "\a"
