name: Bug report
description: Report bugs
labels: 'bug'
assignees: 'TylerMS887'
body:
- type: markdown
  attributes:
    value: "For bug reports related to nano itself, please report the issue to GNU's bug tracker. For bug reports related to the highlighters built into your system, please contact your distribution's developers or submit a report on their bug tracker (e.g. use `reportbug` for Debian)."
- type: input
  id: prevalence
  attributes:
    label: Expected behaviour
    description: "What did you expect when nano is highlighting?"
    placeholder: "nano highlights Dart code"
  validations:
    required: true
- type: input
  id: prevalence
  attributes:
    label: Actual behaviour
    description: "What happened instead?"
    placeholder: "Dart code is not highlighted"
  validations:
    required: true
