name: New Language Requester
description: Request that a new language be added
labels: ["new language"]
assignees: ["TylerMS887"]

body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to the New Language Requester!
        **Please note that esoteric languages are not acceptable and will be declined.**
        However, markup, configuration, and command line languages are acceptable.
        New languages will be introduced into the `dev` Git branch.
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: "Please thoroughly read and tick these requirements before you submit this request."
      options:
        - label: This is not an esoteric language. Esoteric languages are not accepted into nano-highlight for obvious reasons.
          required: true
  - type: input
    id: name
    attributes:
      label: Language name
      placeholder: reStructuredText
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example code
      placeholder: "Insert an example of a program in the language here. This should not be the nano configuration for the highlighter."
      render: text
      placeholder: 'print "Hello World!"'
    validations:
      required: true
